### PR TITLE
Rebase the TiKV branch on to master

### PR DESCRIPTION
**Pull request by nrc**
So, some of our changes got upstreamed, but did not (in particular, io and mem load). So rather than use the old tikv branch, I rebased it to current sysinfo master. I've removed some code which has alternatives in upstream. I think that we can work to upstream the other stuff, but in the meantime I need something so I can run TiKV tests on my machine.

Unfortunately, since this is a rebase, it cannot be merged with the tikv branch. If this PR passes review I propose we create a new branch, tikv2 or something, to land it rather than merging this PR into our master.

PTAL @lonng

### CODE REVIEW

**Comment by lonng** [comment]
Hi, @nrc Can we move some changes which cannot be merged to upstream to an individual repository? And use upstream `sysinfo` in TiKV directly. And the new repo (how about `sysload`?) is used to maintain load functions, which can be reused by others and reduce the complexity of maintenance.

**Comment by GuillaumeGomez** [comment]
For information: I intend to add I/O information at some point. But in the meantime, you'll have to continue using your own code.

**Comment by nrc** [comment]
> Hi, @nrc Can we move some changes which cannot be merged to upstream to an individual repository? 

We could, but I think not now - this PR is an improvement on the current situation, and the better long-term solution is to upstream everything. If that is not possible (I think it should be), then we can make another repo.

**Review by lonng — APPROVED** [review]
LGTM

**Comment by nrc** [comment]
This is now https://github.com/tikv/sysinfo/tree/tikv2

**Pull request closed without merging**
